spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/zip_logistics1?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080
  address: 0.0.0.0

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 864000000


opencage:
  api:
    key: ${OPENCAGE_API_KEY}

direction:
  api:
    key: ${DIRECTION_API_KEY}

weather:
  api:
    key: ${WEATHER_API_KEY}